# Generated by Django 2.0 on 2018-07-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=200)),
                ('country', models.IntegerField(null=True)),
                ('currency_symbol', models.CharField(max_length=30, null=True)),
                ('is_active', models.BooleanField(default=1)),
            ],
        ),
    ]
